apiVersion: v1
kind: Service
metadata:
  labels:
    app: stanbic-getting-started
  name: stanbic-getting-started
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stanbic-getting-started