apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-fruits-data
    app.kubernetes.io/instance: quarkus-fruits-data
    app.kubernetes.io/name: quarkus-fruits-data
    app.kubernetes.io/part-of: quarkus-fruits
    app.openshift.io/runtime: java
  name: quarkus-fruits-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-fruits-data
  template:
    metadata:
      labels:
        app: quarkus-fruits-data
    spec:
      containers:
      - name: quarkus-fruits-data
        imagePullPolicy: Always
        image: quay.io/anmir78/quarkus-fruits-data:latest
        env:
        - name: QUARKUS_DATASOURCE_DB_KIND
          value: "postgresql"
        - name: QUARKUS_DATASOURCE_USERNAME
          value: quarkus_fruits
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: "jdbc:postgresql://postgresql:5432/quarkus_fruits"
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
          value: "drop-and-create"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
