apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-fruits-data
  name: quarkus-fruits-data
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-fruits-data
  sessionAffinity: None
  type: ClusterIP